---
- name: Collect the hosts
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  environment: "{{ environment_vars }}"

  tasks:

    - name: Clear SMFDUMPS
      zos_operator:
        cmd: "\\$pojq,jm=SMFDUMPS"
      register: content
      ignore_errors: yes

    - name: Response for command 
      debug:
        msg: "{{ content }}"

    - name: Clear SMFCLEAR
      zos_operator:
        cmd: "\\$pojq,jm=SMFCLEAR"
      register: content
      ignore_errors: yes

    - name: Response for command 
      debug:
        msg: "{{ content }}"
