---
- name: Collect the hosts
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: False
  
  environment: "{{ environment_vars }}"

  tasks:
    - name: Clear SMFDUMPS
      zos_operator:
        cmd: "\\$pojq,jm=SMFDUMPS"
      register: content

    - name: Clear SMFCLEAR
      zos_operator:
        cmd: "\\$pojq,jm=SMFCLEAR"
      register: content

    - name: Clear DEFRAG
      zos_operator:
        cmd: "\\$pojq,jm=DEFRAG"
      register: content

    - name: Clear CTMTDAY
      zos_operator:
        cmd: "\\$pojq,jm=CTMTDAY"
      register: content

    - name: Clear CTDNDAY
      zos_operator:
        cmd: "\\$pojq,jm=CTDNDAY"
      register: content

    - name: Clear D21NDAY
      zos_operator:
        cmd: "\\$pojq,jm=D21NDAY"
      register: content

    - name: Clear C21TDAY
      zos_operator:
        cmd: "\\$pojq,jm=C21TDAY"
      register: content

    - name: Clear MIGDEL
      zos_operator:
        cmd: "\\$pojq,jm=MIGDEL"
      register: content

    - name: Clear TSO Users
      zos_operator:
        cmd: "\\$pt1-9999"
      register: content