###############################################################################
# © Copyright IBM Corporation 2020, 2021, 2022
###############################################################################

###############################################################################
# This sample playbook demonstrates how to submit jobs, query and retrieve job
# output using modules included in the Red Hat Ansible Certified  Content for
# IBM Z core collection.
#
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventories submit_query_retrieve.yaml
#
#  Additional facts for this playbook can be configured to override the defaults
#  by reviewing the "Fact setting" section of this playbook, for example,
#  `data_set_name`.
#
# Requirements:
#   IBM z/OS core collection 1.1.0 or later # FIXME - update to correct version.
#
# Configure:
#   tgt_tmp_dir - this is the USS directory on the target which will be written
#                 to for this example.
# Optional:
#   data_set_name - this is the data set name that will be created during
#                   execution of this sample.
#   job_name - this is the job name what will be used in this sample, if you
#              change the HELLO.JCL job name, you must update this variable
###############################################################################

---
- name: Basic information
  hosts: all
  gather_facts: true
  vars:
    tgt_tmp_dir: "/tmp"
    job_name: "HELLO"
  environment: "{{ environment_vars }}"

  tasks:
    # Get some facts
    - name: get facts
      ibm.ibm_zos_core.zos_gather_facts:
      register: zos_facts 
        
    # ##########################################################################
    # Generate a temporary data set name
    # ##########################################################################
    - name: Create temp data set name
      ansible.builtin.command: "mvstmp {{ ansible_user | upper }}"
      register: tmp_ds

    # ##########################################################################
    # Fact setting for use by this playbook
    # ##########################################################################
    - name: Setting fact `data_set_name` for use by this sample
      ansible.builtin.set_fact:
        data_set_name: "{{ tmp_ds.stdout }}"

    - name: Fact `data_set_name` set with value
      ansible.builtin.debug:
        msg: "{{ data_set_name }}"

    - name: Create a PDS data set {{ data_set_name }}
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ data_set_name }}"
        type: pds
        size: 5M
        format: fb
        record_length: 80
        replace: true
      register: result

    - name: Response for create a PDS data set {{ data_set_name }}
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Create a PDS member and replace if member exist
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ data_set_name }}(MEM1)"
        type: MEMBER
        replace: true
      register: result

    - name: Response for create a PDS member and replace if member exist
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Ensure JCL folder exists in USS to manage JCL
      ansible.builtin.file:
        path: "{{ tgt_tmp_dir }}/ansible/jcl"
        state: directory

    - name: Response for ensure JCL folder exists in USS to manage JCL
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Write HELLO JCL to USS in {{ tgt_tmp_dir }}/ansible/jcl/HELLO"
        on target {{ inventory_hostname }}
      ibm.ibm_zos_core.zos_copy:
        src: "{{ playbook_dir }}/files/HELLO.jcl"
        dest: "{{ tgt_tmp_dir }}/ansible/jcl/HELLO"
        force: true
      register: result

    - name: Response for write HELLO JCL to USS
        in {{ tgt_tmp_dir }}/ansible/jcl/HELLO" on
        target {{ inventory_hostname }}
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Populate {{ data_set_name }} 
        in {{ tgt_tmp_dir }}/ansible/jcl
      ibm.ibm_zos_core.zos_copy:
        src: "{{ tgt_tmp_dir }}/ansible/jcl/HELLO"
        remote_src: true
        dest: "{{ data_set_name }}(MEM1)"
        force: true
      register: result

    - name: Response for populate {{ data_set_name }}
        USS file in {{ tgt_tmp_dir }}/ansible/jcl
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Submit the JCL {{ data_set_name }}
      ibm.ibm_zos_core.zos_job_submit:
        src: "{{ data_set_name }}(MEM1)"
        location: DATA_SET
        wait_time_s: 30
      register: result

    - name: Response for submit the JCL {{ data_set_name }}
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Setting fact `job_id_pds` for id of job submitted above
      ansible.builtin.set_fact:
        job_id_pds: "{{ result.jobs[0].job_id }}"

    - name: Fact `job_id_pds` set with value
      ansible.builtin.debug:
        msg: "{{ job_id_pds }}"

    - name: Query submitted job by job_id
      ibm.ibm_zos_core.zos_job_query:
        job_id: "{{ job_id_pds }}"
      register: result

    - name: Response for query submitted job by job_id
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Get job output for job {{ job_id_pds }}
      ibm.ibm_zos_core.zos_job_output:
        job_id: "{{ job_id_pds }}"
      register: result

    - name: Response for get job output for job "{{ job_id_pds }}"
        member
      ansible.builtin.debug:
        msg: "{{ result }}"

    ############################################################################
    # +-------------------------------------------------------------------------
    # | Clean up - remove JCL files from USS, delete PDS.
    # +-------------------------------------------------------------------------
    ############################################################################

    - name: Remove {{ job_name }} JCL and folder on USS target
      ansible.builtin.file:
        path: "{{ tgt_tmp_dir }}/ansible"
        state: absent
      register: result

    - name: Response for remove {{ job_name }} JCL and folder on
            USS target
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Delete data set {{ data_set_name }}
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ data_set_name }}"
        state: absent
      register: result

    - name: Response for delete data set {{ data_set_name }}
      ansible.builtin.debug:
        msg: "{{ result }}"
