---
- name: Install INCONTROL Licenses
  hosts: all
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:
    - name: Terminate INCONTROL
      ibm.ibm_zos_core.zos_job_submit:
        src: TOMMY.JCL.CNTL(CTMKILL)
        remote_src: true
        wait_time: 120
        return_output: false
      register: response

    - name: Pause for system to come down
      ansible.builtin.pause:
        minutes: 2

    - name: Remove CTB license
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ IOAPREF }}.PARM(PASCTB)"
        state: absent
        type: member
        force: true

    - name: Remove CTD license
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ IOAPREF }}.PARM(PASCTD)"
        state: absent
        type: member
        force: true

    - name: Remove CTJ license
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ IOAPREF }}.PARM(PASCTJ)"
        state: absent
        type: member
        force: true

    - name: Remove CTM license
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ IOAPREF }}.PARM(PASCTM)"
        state: absent
        type: member
        force: true

    - name: Remove CTO license
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ IOAPREF }}.PARM(PASCTO)"
        state: absent
        type: member
        force: true

    - name: Remove CTR license
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ IOAPREF }}.PARM(PASCTR)"
        state: absent
        type: member
        force: true

    - name: Remove CTT license
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ IOAPREF }}.PARM(PASCTT)"
        state: absent
        type: member
        force: true

    - name: Remove CTV license
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ IOAPREF }}.PARM(PASCTV)"
        state: absent
        type: member
        force: true

    - name: Remove CTD-IMG license
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ IOAPREF }}.PARM(PASDIMG)"
        state: absent
        type: member
        force: true

    - name: Remove CTD-POD license
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ IOAPREF }}.PARM(PASPOD)"
        state: absent
        type: member
        force: true

    - name: Pause for system to free parmlib
      ansible.builtin.pause:
        minutes: 1

    - name: "Copy local license files to PARMLIB"
      ibm.ibm_zos_core.zos_copy:
        src: "{{ playbook_dir }}/files"
        dest: "{{ IOAPREF }}.PARM"
        encoding:
          from: ISO8859-1
          to: IBM-1047
      register: result_copy_dir

    - name: "Response for copy license files to PARMLIB"
      ansible.builtin.debug:
        var: result_copy_dir

    - name: Restart IOA
      ibm.ibm_zos_core.zos_job_submit:
        src: TOMMY.JCL.CNTL(CTMGO)
        remote_src: true
        wait_time: 120
        return_output: false
      register: response
