###############################################################################
# © Copyright IBM Corporation 2020
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory submit_query_output_by_id.yaml
###############################################################################

---
- hosts: all
  gather_facts: false
  vars:
    tgt_tmp_dir: "/tmp"
    job_name: "HELLO"
  environment: "{{ environment_vars }}"

  tasks:
    - name: Copy a local file to a PDS member and convert encoding
      ibm.ibm_zos_core.zos_copy:
        src: "{{playbook_dir}}/files/HELLO.jcl"
        dest: "/u/tommy/hello.jcl"
        force: True
        encoding:
          from: UTF-8
          to: IBM-1047

    - name: Submit JCL
      ibm.ibm_zos_core.zos_job_submit:
        src: "/u/tommy/hello.jcl"
        location: USS
#       src: TOMMY.JCL.CNTL(HELLO)
#       location: DATA_SET
#       encoding:
#         from: UTF-8
#         to: ISO-8859-1
      register: result

