all:
  hosts:
    gold1:
      ansible_host: 71.27.82.210
      ansible_user: tommy
      ansible_python_interpreter: "{{ PYZ }}/bin/python3"
      environment: "{{ environment_vars }}"
    z24:
      ansible_user: tommy
      ansible_host: 10.1.101.2
      ansible_python_interpreter: "{{ PYZ }}/bin/python3"
      environment: "{{ environment_vars }}"
    zdt:
      ansible_user: tommy
      ansible_host: zdt
      ansible_python_interpreter: "{{ PYZ }}/bin/python3"
      environment: "{{ environment_vars }}"
