      PYZ: "/usr/lpp/IBM/cyp/v3r9/pyz"
      ZOAU: "/usr/lpp/IBM/zoautil"

      ansible_host: 13.52.169.117
      ansible_user: tommy
      ansible_python_interpreter: "{{ PYZ }}/bin/python3"
      ansible_remote_tmp: "/tmp"
      environment: "{{ environment_vars }}"
