      PYZ: "/usr/lpp/IBM/cyp/v3r9/pyz"
      ZOAU: "/usr/lpp/IBM/zoautil"

      ansible_host: 71.27.82.209
      ansible_user: tommy
      ansible_python_interpreter: "{{ PYZ }}/bin/python3"
      environment: "{{ environment_vars }}"
###WARNING - python and zoautil not installed here