PYZ: "/usr/lpp/IBM/cyp/v3r9/pyz"
ZOAU: "/usr/lpp/IBM/zoautil"
ansible_user: tommy
ansible_host: 10.1.101.2
ansible_ssh_timeout: 60
ansible_python_interpreter: "{{ PYZ }}/bin/python3"
environment: "{{ environment_vars }}"
