PYZ: "/usr/lpp/IBM/cyp/v3r12/pyz"
ZOAU: "/usr/lpp/IBM/zoautil"
IOAPREF: "IOA921"
ansible_user: tommy
ansible_host: zdt31
ansible_port: 65522
ansible_python_interpreter: "{{ PYZ }}/bin/python3"
environment: "{{ environment_vars }}"
