# Copy this file to a private inventory and set environment-specific values.
PYZ: "/usr/lpp/IBM/cyp/v3r12/pyz"
ZOAU: "/usr/lpp/IBM/zoautil"
ansible_host: zos_target_address
ansible_user: zos_target_username
ansible_python_interpreter: "{{ PYZ }}/bin/python3"
environment: "{{ environment_vars }}"
